version: "3"

services:
  database:
    container_name: GameShelf-DEV
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 9090:5432
    expose:
      - 9090

  db_test:
    container_name: GameShelf-TEST
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 9191:5432

volumes:
  db_data:
