version: "3"

services:
  database:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gameshelf
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
